// Code written by Gabriel Mailhot, 24/08/2023.

namespace TheBestCombatMod.Concept
{
   public interface UnseatValue
   {
      string ABDOMEN_BLUNT_SWINGING_v2v6T_Value { get; }
      string ABDOMEN_BLUNT_THRUSTING_6gLsx_Value { get; }
      string ABDOMEN_CUT_SWINGING_tRqGA_Value { get; }
      string ABDOMEN_CUT_THRUSTING_eypTb_Value { get; }
      string ABDOMEN_PIERCE_SWINGING_VTO6S_Value { get; }
      string ABDOMEN_PIERCE_THRUSTING_suxMY_Value { get; }
      string ARMS_BLUNT_SWINGING_zwGj0_Value { get; }
      string ARMS_BLUNT_THRUSTING_E9s8D_Value { get; }
      string ARMS_CUT_SWINGING_eMIfX_Value { get; }
      string ARMS_CUT_THRUSTING_uHDMI_Value { get; }
      string ARMS_PIERCE_SWINGING_ScPD3_Value { get; }
      string ARMS_PIERCE_THRUSTING_7R3oW_Value { get; }
      string Base_Stagger_Force_Dagger_n1XdZ_Value { get; }
      string Base_Stagger_Force_Javelin_Xsa8Z_Value { get; }
      string Base_Stagger_Force_Mace_gFe0e_Value { get; }
      string Base_Stagger_Force_OneHandedAxe_4DlEy_Value { get; }
      string Base_Stagger_Force_OneHandedPolearm_7N5Ag_Value { get; }
      string Base_Stagger_Force_OneHandedSword_w5XQZ_Value { get; }
      string Base_Stagger_Force_Pick_vtQof_Value { get; }
      string Base_Stagger_Force_Stone_q0Ak2_Value { get; }
      string Base_Stagger_Force_ThrowingAxe_GuSl7_Value { get; }
      string Base_Stagger_Force_ThrowingKnife_5hKU8_Value { get; }
      string Base_Stagger_Force_TwoHandedAxe_nA05d_Value { get; }
      string Base_Stagger_Force_TwoHandedMace_E78By_Value { get; }
      string Base_Stagger_Force_TwoHandedPolearm_2SCK0_Value { get; }
      string Base_Stagger_Force_TwoHandedSword_cU7uE_Value { get; }
      string CHEST_BLUNT_SWINGING_Ip0TE_Value { get; }
      string CHEST_BLUNT_THRUSTING_ktCEu_Value { get; }
      string CHEST_CUT_SWINGING_sQmx7_Value { get; }
      string CHEST_CUT_THRUSTING_dNomI_Value { get; }
      string CHEST_PIERCE_SWINGING_6ssat_Value { get; }
      string CHEST_PIERCE_THRUSTING_ybixm_Value { get; }
      string DAGGER_SWING_BLUNT_AGAINST_CHAINMAIL_zI7qM_Value { get; }
      string DAGGER_SWING_BLUNT_AGAINST_CLOTH_iM0qR_Value { get; }
      string DAGGER_SWING_BLUNT_AGAINST_LEATHER_yA2wC_Value { get; }
      string DAGGER_SWING_BLUNT_AGAINST_PLATE_qB4fS_Value { get; }
      string DAGGER_SWING_CUT_AGAINST_CHAINMAIL_tY3rN_Value { get; }
      string DAGGER_SWING_CUT_AGAINST_CLOTH_J8s2F_Value { get; }
      string DAGGER_SWING_CUT_AGAINST_LEATHER_bD1mK_Value { get; }
      string DAGGER_SWING_CUT_AGAINST_PLATE_lO6wE_Value { get; }
      string DAGGER_THRUST_BLUNT_AGAINST_CHAINMAIL_xU9eP_Value { get; }
      string DAGGER_THRUST_BLUNT_AGAINST_CLOTH_hN7Ye_Value { get; }
      string DAGGER_THRUST_BLUNT_AGAINST_LEATHER_fR6jP_Value { get; }
      string DAGGER_THRUST_BLUNT_AGAINST_PLATE_nZ8uR_Value { get; }
      string DAGGER_THRUST_PIERCE_AGAINST_CHAINMAIL_cG5vL_Value { get; }
      string DAGGER_THRUST_PIERCE_AGAINST_CLOTH_3HkLg_Value { get; }
      string DAGGER_THRUST_PIERCE_AGAINST_LEATHER_9sT4p_Value { get; }
      string DAGGER_THRUST_PIERCE_AGAINST_PLATE_vX2jD_Value { get; }
      string HEAD_BLUNT_SWINGING_8VPtS_Value { get; }
      string HEAD_BLUNT_THRUSTING_UzQhf_Value { get; }
      string HEAD_CUT_SWINGING_05zN2_Value { get; }
      string HEAD_CUT_THRUSTING_IgazM_Value { get; }
      string HEAD_PIERCE_SWINGING_JMWpz_Value { get; }
      string HEAD_PIERCE_THRUSTING_pMa5J_Value { get; }
      string Impact_Dismount_Chance_Attacker_Healthier_wK2Fb_Value { get; }
      string Impact_Dismount_Chance_Attacker_Heavier_uiezF_Value { get; }
      string Impact_Dismount_Chance_Attacker_Is_Woman_aUufU_Value { get; }
      string Impact_Dismount_Chance_Attacker_Stronger_W3JH2_Value { get; }
      string Impact_Dismount_Chance_Blow_Critical_BLUNT_TI8bQ_Vlaue { get; }
      string Impact_Dismount_Chance_Blow_Critical_CUT_d461x_Value { get; }
      string Impact_Dismount_Chance_Blow_Critical_PIERCE_WDaWG_Value { get; }
      string Impact_Dismount_Chance_Thrust_Tip_Hit_cGmzd_Value { get; }
      string Impact_Dismount_Chance_VictimDidNot_Raise_Guard_h8WXN_Value { get; }
      string Impact_Dismount_Chance_Weapon_Inertia_aLp7H_Value { get; }
      string Increases_Inertia_Given_Strike_On_Horseback_lqO62_Value { get; }
      string JAVELIN_SWING_BLUNT_AGAINST_CHAINMAIL_pA3vR_Value { get; }
      string JAVELIN_SWING_BLUNT_AGAINST_CLOTH_tA1vZ_Value { get; }
      string JAVELIN_SWING_BLUNT_AGAINST_LEATHER_yM4aI_Value { get; }
      string JAVELIN_SWING_BLUNT_AGAINST_PLATE_tZ7uO_Value { get; }
      string JAVELIN_SWING_CUT_AGAINST_CHAINMAIL_nB7eU_Value { get; }
      string JAVELIN_SWING_CUT_AGAINST_CLOTH_rN5uX_Value { get; }
      string JAVELIN_SWING_CUT_AGAINST_LEATHER_iK6xO_Value { get; }
      string JAVELIN_SWING_CUT_AGAINST_PLATE_rC4dP_Value { get; }
      string JAVELIN_THRUST_BLUNT_AGAINST_CHAINMAIL_zD5tL_Value { get; }
      string JAVELIN_THRUST_BLUNT_AGAINST_CLOTH_kY3gW_Value { get; }
      string JAVELIN_THRUST_BLUNT_AGAINST_LEATHER_sU7nJ_Value { get; }
      string JAVELIN_THRUST_BLUNT_AGAINST_PLATE_mY8bF_Value { get; }
      string JAVELIN_THRUST_PIERCE_AGAINST_CHAINMAIL_xF9cV_Value { get; }
      string JAVELIN_THRUST_PIERCE_AGAINST_CLOTH_mC9dH_Value { get; }
      string JAVELIN_THRUST_PIERCE_AGAINST_LEATHER_pE8bQ_Value { get; }
      string JAVELIN_THRUST_PIERCE_AGAINST_PLATE_oX1wM_Value { get; }
      string LEGS_BLUNT_SWINGING_JTLxV_Value { get; }
      string LEGS_BLUNT_THRUSTING_awuSL_Value { get; }
      string LEGS_CUT_SWINGING_xOKtK_Value { get; }
      string LEGS_CUT_THRUSTING_hEsET_Value { get; }
      string LEGS_PIERCE_SWINGING_6DD8t_Value { get; }
      string LEGS_PIERCE_THRUSTING_NblKm_Value { get; }
      string NECK_BLUNT_SWINGING_Z19yv_Value { get; }
      string NECK_BLUNT_THRUSTING_yZEV1_Value { get; }
      string NECK_CUT_SWINGING_OJ42D_Value { get; }
      string NECK_CUT_THRUSTING_JDsUb_Value { get; }
      string NECK_PIERCE_SWINGING_16Tqb_Value { get; }
      string NECK_PIERCE_THRUSTING_PwjyT_Value { get; }
      string ONE_HANDED_AXE_SWING_BLUNT_AGAINST_CHAINMAIL_mF2hZ_Value { get; }
      string ONE_HANDED_AXE_SWING_BLUNT_AGAINST_CLOTH_yE7rP_Value { get; }
      string ONE_HANDED_AXE_SWING_BLUNT_AGAINST_LEATHER_cD9fY_Value { get; }
      string ONE_HANDED_AXE_SWING_BLUNT_AGAINST_PLATE_vU7gQ_Value { get; }
      string ONE_HANDED_AXE_SWING_CUT_AGAINST_CHAINMAIL_rJ9xI_Value { get; }
      string ONE_HANDED_AXE_SWING_CUT_AGAINST_CLOTH_nJ2hQ_Value { get; }
      string ONE_HANDED_AXE_SWING_CUT_AGAINST_LEATHER_aT5zH_Value { get; }
      string ONE_HANDED_AXE_SWING_CUT_AGAINST_PLATE_tJ3hV_Value { get; }
      string ONE_HANDED_AXE_THRUST_BLUNT_AGAINST_CHAINMAIL_kM3dV_Value { get; }
      string ONE_HANDED_AXE_THRUST_BLUNT_AGAINST_CLOTH_pC9xW_Value { get; }
      string ONE_HANDED_AXE_THRUST_BLUNT_AGAINST_LEATHER_jN1xL_Value { get; }
      string ONE_HANDED_AXE_THRUST_BLUNT_AGAINST_PLATE_lN8xG_Value { get; }
      string ONE_HANDED_AXE_THRUST_PIERCE_AGAINST_CHAINMAIL_qU7gT_Value { get; }
      string ONE_HANDED_AXE_THRUST_PIERCE_AGAINST_CLOTH_hR6zK_Value { get; }
      string ONE_HANDED_AXE_THRUST_PIERCE_AGAINST_LEATHER_wB4mV_Value { get; }
      string ONE_HANDED_AXE_THRUST_PIERCE_AGAINST_PLATE_zB4mR_Value { get; }
      string ONE_HANDED_MACE_SWING_BLUNT_AGAINST_CHAINMAIL_pF1wK_Value { get; }
      string ONE_HANDED_MACE_SWING_BLUNT_AGAINST_CLOTH_uB9fS_Value { get; }
      string ONE_HANDED_MACE_SWING_BLUNT_AGAINST_LEATHER_hR5vQ_Value { get; }
      string ONE_HANDED_MACE_SWING_BLUNT_AGAINST_PLATE_lA8hY_Value { get; }
      string ONE_HANDED_MACE_SWING_CUT_AGAINST_CHAINMAIL_jY7gI_Value { get; }
      string ONE_HANDED_MACE_SWING_CUT_AGAINST_CLOTH_mQ7aN_Value { get; }
      string ONE_HANDED_MACE_SWING_CUT_AGAINST_LEATHER_qJ9cK_Value { get; }
      string ONE_HANDED_MACE_SWING_CUT_AGAINST_PLATE_zE3dX_Value { get; }
      string ONE_HANDED_MACE_THRUST_BLUNT_AGAINST_CHAINMAIL_wD8eV_Value { get; }
      string ONE_HANDED_MACE_THRUST_BLUNT_AGAINST_CLOTH_tE5rW_Value { get; }
      string ONE_HANDED_MACE_THRUST_BLUNT_AGAINST_LEATHER_kP6xH_Value { get; }
      string ONE_HANDED_MACE_THRUST_BLUNT_AGAINST_PLATE_vB9fQ_Value { get; }
      string ONE_HANDED_MACE_THRUST_PIERCE_AGAINST_CHAINMAIL_aT2mZ_Value { get; }
      string ONE_HANDED_MACE_THRUST_PIERCE_AGAINST_CLOTH_bN3hU_Value { get; }
      string ONE_HANDED_MACE_THRUST_PIERCE_AGAINST_LEATHER_gM4zD_Value { get; }
      string ONE_HANDED_MACE_THRUST_PIERCE_AGAINST_PLATE_nC6zT_Value { get; }
      string ONE_HANDED_POLEARM_SWING_BLUNT_AGAINST_CHAINMAIL_sR4zT_Value { get; }
      string ONE_HANDED_POLEARM_SWING_BLUNT_AGAINST_CLOTH_sJ4hQ_Value { get; }
      string ONE_HANDED_POLEARM_SWING_BLUNT_AGAINST_LEATHER_aF5zT_Value { get; }
      string ONE_HANDED_POLEARM_SWING_BLUNT_AGAINST_PLATE_qM5zE_Value { get; }
      string ONE_HANDED_POLEARM_SWING_CUT_AGAINST_CHAINMAIL_tA8hK_Value { get; }
      string ONE_HANDED_POLEARM_SWING_CUT_AGAINST_CLOTH_lM2dH_Value { get; }
      string ONE_HANDED_POLEARM_SWING_CUT_AGAINST_LEATHER_eJ9xI_Value { get; }
      string ONE_HANDED_POLEARM_SWING_CUT_AGAINST_PLATE_hU9gT_Value { get; }
      string ONE_HANDED_POLEARM_THRUST_BLUNT_AGAINST_CHAINMAIL_mC6xV_Value { get; }
      string ONE_HANDED_POLEARM_THRUST_BLUNT_AGAINST_CLOTH_kC9xT_Value { get; }
      string ONE_HANDED_POLEARM_THRUST_BLUNT_AGAINST_LEATHER_xM3zV_Value { get; }
      string ONE_HANDED_POLEARM_THRUST_BLUNT_AGAINST_PLATE_bT2dK_Value { get; }
      string ONE_HANDED_POLEARM_THRUST_PIERCE_AGAINST_CHAINMAIL_nE2dG_Value { get; }
      string ONE_HANDED_POLEARM_THRUST_PIERCE_AGAINST_CLOTH_dR6zE_Value { get; }
      string ONE_HANDED_POLEARM_THRUST_PIERCE_AGAINST_LEATHER_rU7gK_Value { get; }
      string ONE_HANDED_POLEARM_THRUST_PIERCE_AGAINST_PLATE_yE6xJ_Value { get; }
      string ONE_HANDED_SWORD_SWING_BLUNT_AGAINST_CHAINMAIL_RgN3k_Value { get; }
      string ONE_HANDED_SWORD_SWING_BLUNT_AGAINST_CLOTH_64Lhv_Value { get; }
      string ONE_HANDED_SWORD_SWING_BLUNT_AGAINST_LEATHER_tiuYy_Value { get; }
      string ONE_HANDED_SWORD_SWING_BLUNT_AGAINST_PLATE_qLDxk_Value { get; }
      string ONE_HANDED_SWORD_SWING_CUT_AGAINST_CHAINMAIL_UdBiS_Value { get; }
      string ONE_HANDED_SWORD_SWING_CUT_AGAINST_CLOTH_U1GgF_Value { get; }
      string ONE_HANDED_SWORD_SWING_CUT_AGAINST_LEATHER_HXuje_Value { get; }
      string ONE_HANDED_SWORD_SWING_CUT_AGAINST_PLATE_jgMZR_Value { get; }
      string ONE_HANDED_SWORD_THRUST_BLUNT_AGAINST_CHAINMAIL_Unb84_Value { get; }
      string ONE_HANDED_SWORD_THRUST_BLUNT_AGAINST_CLOTH_oGmnS_Value { get; }
      string ONE_HANDED_SWORD_THRUST_BLUNT_AGAINST_LEATHER_ljFbE_Value { get; }
      string ONE_HANDED_SWORD_THRUST_BLUNT_AGAINST_PLATE_9DpM5_Value { get; }
      string ONE_HANDED_SWORD_THRUST_PIERCE_AGAINST_CHAINMAIL_2Ng91_Value { get; }
      string ONE_HANDED_SWORD_THRUST_PIERCE_AGAINST_CLOTH_kWNK9_Value { get; }
      string ONE_HANDED_SWORD_THRUST_PIERCE_AGAINST_LEATHER_txKI6_Value { get; }
      string ONE_HANDED_SWORD_THRUST_PIERCE_AGAINST_PLATE_GDD4U_Value { get; }
      string PEASANT_REDUCE_PROBABILITY_BY { get; }
      string PICK_SWING_BLUNT_AGAINST_CHAINMAIL_kF9cR_Value { get; }
      string PICK_SWING_BLUNT_AGAINST_CLOTH_yB7gR_Value { get; }
      string PICK_SWING_BLUNT_AGAINST_LEATHER_sU5zH_Value { get; }
      string PICK_SWING_BLUNT_AGAINST_PLATE_lA8hY_Value { get; }
      string PICK_SWING_CUT_AGAINST_CHAINMAIL_xU3gA_Value { get; }
      string PICK_SWING_CUT_AGAINST_CLOTH_nF5zV_Value { get; }
      string PICK_SWING_CUT_AGAINST_LEATHER_bJ2hT_Value { get; }
      string PICK_SWING_CUT_AGAINST_PLATE_zE3dX_Value { get; }
      string PICK_THRUST_BLUNT_AGAINST_CHAINMAIL_aN8xS_Value { get; }
      string PICK_THRUST_BLUNT_AGAINST_CLOTH_qM2dA_Value { get; }
      string PICK_THRUST_BLUNT_AGAINST_LEATHER_pC9xV_Value { get; }
      string PICK_THRUST_BLUNT_AGAINST_PLATE_vB9fQ_Value { get; }
      string PICK_THRUST_PIERCE_AGAINST_CHAINMAIL_eB4mW_Value { get; }
      string PICK_THRUST_PIERCE_AGAINST_CLOTH_xC9xT_Value { get; }
      string PICK_THRUST_PIERCE_AGAINST_LEATHER_tR6zE_Value { get; }
      string PICK_THRUST_PIERCE_AGAINST_PLATE_nC6zT_Value { get; }
      string Resistance_Strength_FORMIDABLE_3l4Jw_Value { get; }
      string Resistance_Strength_LOW_sMtnq_Value { get; }
      string Resistance_Strength_MODERATE_gEghq_Value { get; }
      string Resistance_Strength_NONE_P5V27_Value { get; }
      string Resistance_Strength_STRONG_AX48F_Value { get; }
      string SHOULDERS_BLUNT_SWINGING_TplnH_Value { get; }
      string SHOULDERS_BLUNT_THRUSTING_gqk9L_Value { get; }
      string SHOULDERS_CUT_SWINGING_8yoXK_Value { get; }
      string SHOULDERS_CUT_THRUSTING_2Y1ez_Value { get; }
      string SHOULDERS_PIERCE_SWINGING_HoWbh_Value { get; }
      string SHOULDERS_PIERCE_THRUSTING_UhpJO_Value { get; }
      string Stagger_Strength_FORMIDABLE_VCMCx_Value { get; }
      string Stagger_Strength_LOW_iDpZg_Value { get; }
      string Stagger_Strength_MINIMAL_l4VjY_Vlaue { get; }
      string Stagger_Strength_MODERATE_g9CEb_Value { get; }
      string Stagger_Strength_NONE_wAKKZ_Value { get; }
      string Stagger_Strength_STRONG_Ptkiw_Value { get; }
      string STONE_SWING_BLUNT_AGAINST_CHAINMAIL_bQ5zE_Value { get; }
      string STONE_SWING_BLUNT_AGAINST_CLOTH_kE9xR_Value { get; }
      string STONE_SWING_BLUNT_AGAINST_LEATHER_uN9gS_Value { get; }
      string STONE_SWING_BLUNT_AGAINST_PLATE_kN4zI_Value { get; }
      string STONE_SWING_CUT_AGAINST_CHAINMAIL_aU9gR_Value { get; }
      string STONE_SWING_CUT_AGAINST_CLOTH_jN5uG_Value { get; }
      string STONE_SWING_CUT_AGAINST_LEATHER_pC3xV_Value { get; }
      string STONE_SWING_CUT_AGAINST_PLATE_zC8xG_Value { get; }
      string STONE_THRUST_BLUNT_AGAINST_CHAINMAIL_fM4zG_Value { get; }
      string STONE_THRUST_BLUNT_AGAINST_CLOTH_zC8xI_Value { get; }
      string STONE_THRUST_BLUNT_AGAINST_LEATHER_rY8nA_Value { get; }
      string STONE_THRUST_BLUNT_AGAINST_PLATE_nY3hA_Value { get; }
      string STONE_THRUST_PIERCE_AGAINST_CHAINMAIL_dE7rQ_Value { get; }
      string STONE_THRUST_PIERCE_AGAINST_CLOTH_fG4zW_Value { get; }
      string STONE_THRUST_PIERCE_AGAINST_LEATHER_qH4zP_Value { get; }
      string STONE_THRUST_PIERCE_AGAINST_PLATE_tH7xQ_Value { get; }
      string Strike_Sensitivity_For_Abdomen_iNG4j_Value { get; }
      string Strike_Sensitivity_For_Arms_NP7Xe_Value { get; }
      string Strike_Sensitivity_For_Chest_HuSFa_Value { get; }
      string Strike_Sensitivity_For_Head_rGcYE_Value { get; }
      string Strike_Sensitivity_For_Legs_DQndk_Value { get; }
      string Strike_Sensitivity_For_Neck_oMvdW_Value { get; }
      string Strike_Sensitivity_For_Shoulders_WU5Bv_Value { get; }
      string TWO_HANDED_AXE_SWING_BLUNT_AGAINST_CHAINMAIL_tQ5zR_Value { get; }
      string TWO_HANDED_AXE_SWING_BLUNT_AGAINST_CLOTH_mT8xU_Value { get; }
      string TWO_HANDED_AXE_SWING_BLUNT_AGAINST_LEATHER_nC9xI_Value { get; }
      string TWO_HANDED_AXE_SWING_BLUNT_AGAINST_PLATE_dH7gV_Value { get; }
      string TWO_HANDED_AXE_SWING_CUT_AGAINST_CHAINMAIL_aH8xV_Value { get; }
      string TWO_HANDED_AXE_SWING_CUT_AGAINST_CLOTH_sN4zR_Value { get; }
      string TWO_HANDED_AXE_SWING_CUT_AGAINST_LEATHER_wG6xR_Value { get; }
      string TWO_HANDED_AXE_SWING_CUT_AGAINST_PLATE_iE8xL_Value { get; }
      string TWO_HANDED_AXE_THRUST_BLUNT_AGAINST_CHAINMAIL_rT3zG_Value { get; }
      string TWO_HANDED_AXE_THRUST_BLUNT_AGAINST_CLOTH_kD9xL_Value { get; }
      string TWO_HANDED_AXE_THRUST_BLUNT_AGAINST_LEATHER_tH3zA_Value { get; }
      string TWO_HANDED_AXE_THRUST_BLUNT_AGAINST_PLATE_fT4zA_Value { get; }
      string TWO_HANDED_AXE_THRUST_PIERCE_AGAINST_CHAINMAIL_bN4zT_Value { get; }
      string TWO_HANDED_AXE_THRUST_PIERCE_AGAINST_CLOTH_fU5zH_Value { get; }
      string TWO_HANDED_AXE_THRUST_PIERCE_AGAINST_LEATHER_vE7gV_Value { get; }
      string TWO_HANDED_AXE_THRUST_PIERCE_AGAINST_PLATE_sU9gH_Value { get; }
      string TWO_HANDED_MACE_SWING_BLUNT_AGAINST_CHAINMAIL_mJ2hU_Value { get; }
      string TWO_HANDED_MACE_SWING_BLUNT_AGAINST_CLOTH_gU5zV_Value { get; }
      string TWO_HANDED_MACE_SWING_BLUNT_AGAINST_LEATHER_kT3zR_Value { get; }
      string TWO_HANDED_MACE_SWING_BLUNT_AGAINST_PLATE_pS5zE_Value { get; }
      string TWO_HANDED_MACE_SWING_CUT_AGAINST_CHAINMAIL_lR5zH_Value { get; }
      string TWO_HANDED_MACE_SWING_CUT_AGAINST_CLOTH_qH8xG_Value { get; }
      string TWO_HANDED_MACE_SWING_CUT_AGAINST_LEATHER_mH7gA_Value { get; }
      string TWO_HANDED_MACE_SWING_CUT_AGAINST_PLATE_jC9xR_Value { get; }
      string TWO_HANDED_MACE_THRUST_BLUNT_AGAINST_CHAINMAIL_jG8xT_Value { get; }
      string TWO_HANDED_MACE_THRUST_BLUNT_AGAINST_CLOTH_bN4zA_Value { get; }
      string TWO_HANDED_MACE_THRUST_BLUNT_AGAINST_LEATHER_zE9xL_Value { get; }
      string TWO_HANDED_MACE_THRUST_BLUNT_AGAINST_PLATE_dU6xV_Value { get; }
      string TWO_HANDED_MACE_THRUST_PIERCE_AGAINST_CHAINMAIL_aG6xI_Value { get; }
      string TWO_HANDED_MACE_THRUST_PIERCE_AGAINST_CLOTH_zD9xT_Value { get; }
      string TWO_HANDED_MACE_THRUST_PIERCE_AGAINST_LEATHER_wT4zE_Value { get; }
      string TWO_HANDED_MACE_THRUST_PIERCE_AGAINST_PLATE_bH4zG_Value { get; }
      string TWO_HANDED_POLEARM_SWING_BLUNT_AGAINST_CHAINMAIL_lJ2hT_Value { get; }
      string TWO_HANDED_POLEARM_SWING_BLUNT_AGAINST_CLOTH_vH8xR_Value { get; }
      string TWO_HANDED_POLEARM_SWING_BLUNT_AGAINST_LEATHER_yT3zH_Value { get; }
      string TWO_HANDED_POLEARM_SWING_BLUNT_AGAINST_PLATE_kD3zA_Value { get; }
      string TWO_HANDED_POLEARM_SWING_CUT_AGAINST_CHAINMAIL_fR5zA_Value { get; }
      string TWO_HANDED_POLEARM_SWING_CUT_AGAINST_CLOTH_mD4zE_Value { get; }
      string TWO_HANDED_POLEARM_SWING_CUT_AGAINST_LEATHER_bE7gA_Value { get; }
      string TWO_HANDED_POLEARM_SWING_CUT_AGAINST_PLATE_rN9gR_Value { get; }
      string TWO_HANDED_POLEARM_THRUST_BLUNT_AGAINST_CHAINMAIL_pG8xV_Value { get; }
      string TWO_HANDED_POLEARM_THRUST_BLUNT_AGAINST_CLOTH_yN7xL_Value { get; }
      string TWO_HANDED_POLEARM_THRUST_BLUNT_AGAINST_LEATHER_gN4zG_Value { get; }
      string TWO_HANDED_POLEARM_THRUST_BLUNT_AGAINST_PLATE_mH6xV_Value { get; }
      string TWO_HANDED_POLEARM_THRUST_PIERCE_AGAINST_CHAINMAIL_kG6xU_Value { get; }
      string TWO_HANDED_POLEARM_THRUST_PIERCE_AGAINST_CLOTH_zH4zW_Value { get; }
      string TWO_HANDED_POLEARM_THRUST_PIERCE_AGAINST_LEATHER_cT9xI_Value { get; }
      string TWO_HANDED_POLEARM_THRUST_PIERCE_AGAINST_PLATE_eS4zG_Value { get; }
      string TWO_HANDED_SWORD_SWING_BLUNT_AGAINST_CHAINMAIL_dH8xT_Value { get; }
      string TWO_HANDED_SWORD_SWING_BLUNT_AGAINST_CLOTH_dH8xR_Value { get; }
      string TWO_HANDED_SWORD_SWING_BLUNT_AGAINST_LEATHER_lH8xV_Value { get; }
      string TWO_HANDED_SWORD_SWING_BLUNT_AGAINST_PLATE_lH8xR_Value { get; }
      string TWO_HANDED_SWORD_SWING_CUT_AGAINST_CHAINMAIL_yN7xI_Value { get; }
      string TWO_HANDED_SWORD_SWING_CUT_AGAINST_CLOTH_yN7xG_Value { get; }
      string TWO_HANDED_SWORD_SWING_CUT_AGAINST_LEATHER_tN7xH_Value { get; }
      string TWO_HANDED_SWORD_SWING_CUT_AGAINST_PLATE_tN7xL_Value { get; }
      string TWO_HANDED_SWORD_THRUST_BLUNT_AGAINST_CHAINMAIL_fE4zR_Value { get; }
      string TWO_HANDED_SWORD_THRUST_BLUNT_AGAINST_CLOTH_nE4zA_Value { get; }
      string TWO_HANDED_SWORD_THRUST_BLUNT_AGAINST_LEATHER_xE4zG_Value { get; }
      string TWO_HANDED_SWORD_THRUST_BLUNT_AGAINST_PLATE_xE4zH_Value { get; }
      string TWO_HANDED_SWORD_THRUST_PIERCE_AGAINST_CHAINMAIL_aT9xL_Value { get; }
      string TWO_HANDED_SWORD_THRUST_PIERCE_AGAINST_CLOTH_wT9xP_Value { get; }
      string TWO_HANDED_SWORD_THRUST_PIERCE_AGAINST_LEATHER_wT9xT_Value { get; }
      string TWO_HANDED_SWORD_THRUST_PIERCE_AGAINST_PLATE_wT9xG_Value { get; }
   }
}